# Generated by Django 5.2 on 2025-04-09 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
